# Generated by Django 4.2.4 on 2023-10-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_education_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('website', models.URLField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
                ('twiter', models.URLField(max_length=100)),
                ('facebook', models.URLField(max_length=100)),
                ('youtube', models.URLField(max_length=100)),
                ('linkdin', models.URLField(max_length=100)),
                ('insta', models.URLField(max_length=100)),
            ],
        ),
    ]
